### ISSUE TITLE
handle timestamps of files/directories so that they don't get updated on each rsync run

### ISSUE THREAD

**Issue by ties** [NLnetLabs/krill-sync#25]
As a repository operator I want krill-sync to set a constant timestamp on files so that they do not get modified unnecessarily.

I observe that many RP instances run rsync with flags that sync the timestamp. For example, on my machine, I see the following rsync process:
```
rsync --contimeout=10 --timeout=300 -rltz --delete rsync://[repo]/repo/ [target_dir]
```
I think that the times are also used to detect what files are modified, since `-c` is documented as
```
        -c, --checksum              skip based on checksum, not mod-time & size
```

The timestamp of the files in the repository is set to the time the repository is written. I think this causes rsync clients to change the modification time of each file every time rsync is running (and maybe even transfer them).

**Comment by timbru** [comment]
Right, so you are proposing a fixed, perhaps hardcoded timestamp?

To me it seems a bit wrong to do it this way.. I think it would be better to use one of the following strategies:
1. use a timestamp based on when krill-sync first sees an object
2. use a timestamp based on the 'not-before' time of each object (i.e. parse it)

The first is relatively easy on the 0.2 dev branch and probably good enough. The second is perhaps more correct, but will incur a (much) bigger cost in parsing - well and development - and it could lead to issues if an object cannot be parsed (fall back to strategy 1 then?).

The additional cost to setting the mtime (which is what matters here I guess) is negligible I think - seems to add about 10%.

So, all in all my proposal would be to scope this issue to strategy 1 for now - and perhaps create a follow up issue for strategy 2 if it would be needed at all.

**Comment by ximon18** [comment]
Perhaps I misunderstood but I thought Ties meant only that once written, the timestamp of a file (even if deleted and replaced by an identical file) should not change from the perspective of the serving process (rsyncd/nginx) so that it is not mistakenly perceived to have changed when it has not. I do not think he was proposing a single fixed hard-coded timestamp. But I could be wrong...

**Comment by timbru** [comment]
Ah yes, most likely constant for each **file**. Anyway, I will look at strategy 1... it should be fairly straightforward when I implement issue #27 - then I will need to keep the current files and their metadata anyway - instead of just getting them from XML.

Strategy 2 can be done as a later improvement.

**Comment by ties** [comment]
Indeed - I meant that each file keeps a constant timestamp in each revision of the rsync repository written. My understanding is that `rsync` without `-c` may not re-sync files that changed, but kept their size & date, so choosing one fixed point in time would lead to rare bugs.

For the directories you _can_ choose a fixed timestamp. For example, the RIPE repository uses 1-1-1970:
```
$ rsync rsync://rpki.ripe.net/repository/
...
drwxr-xr-x        4096 2021/06/11 17:01:36 .
-rw-r--r--        1259 2021/05/04 13:31:22 2a7dd1d787d793e4c8af56e197d4eed92af6ba13.cer
-rw-r--r--         555 2021/05/04 13:31:22 ripe-ncc-ta.crl
-rw-r--r--        1796 2021/05/04 13:31:22 ripe-ncc-ta.mft
drwxr-xr-x     1187840 1970/01/01 01:00:00 DEFAULT
drwxr-xr-x        4096 1970/01/01 01:00:00 aca
```

As an aside: It looks like `ETag`s optionally (and also `If-Modified-Since` definitely) use the modification time. So if multiple instances run behind a LB, for RRDP, this can also lead to multiple transfers of `notification.xml`. For `If-None-Match` with one `ETag` I'm not even sure if it converges.

**Comment by timbru** [comment]
> Indeed - I meant that each file keeps a constant timestamp in each revision of the rsync repository written. My understanding is that `rsync` without `-c` may not re-sync files that changed, but kept their size & date, so choosing one fixed point in time would lead to rare bugs.
> 
> For the directories you _can_ choose a fixed timestamp. For example, the RIPE repository uses 1-1-1970:
> 
> ```
> $ rsync rsync://rpki.ripe.net/repository/
> ...
> drwxr-xr-x        4096 2021/06/11 17:01:36 .
> -rw-r--r--        1259 2021/05/04 13:31:22 2a7dd1d787d793e4c8af56e197d4eed92af6ba13.cer
> -rw-r--r--         555 2021/05/04 13:31:22 ripe-ncc-ta.crl
> -rw-r--r--        1796 2021/05/04 13:31:22 ripe-ncc-ta.mft
> drwxr-xr-x     1187840 1970/01/01 01:00:00 DEFAULT
> drwxr-xr-x        4096 1970/01/01 01:00:00 aca
> ```
> 
> My intuition is to stay away from strategy 2 - iirc a repository may contain non-RPKI files.
> 

Sure, aiming for 1.. 2 would only ever work with a fallback to 1.

> As an aside: It looks like `ETag`s optionally (and also `If-Modified-Since` definitely) use the modification time. So if multiple instances run behind a LB, for RRDP, this can also lead to multiple transfers of `notification.xml`. For `If-None-Match` with one `ETag` I'm not even sure if it converges.

Right.. different issue, but replying here.. so far 'If-None-Match' seems to work just fine on the RIPE NCC notification.xml, but then again I hit the CDN and not the back-end servers. The cost of doing an extra fetch from krill-sync is not too bad I would think though - it can work out based on the session and serial that no work is needed.

What I can do is fall back to 'If-Modified-Since' if no 'ETag' was received. According to RFC7232 there is no point in specifying both together: https://datatracker.ietf.org/doc/html/rfc7232#section-3.3

Then.. well if your cluster cannot give me a reliable ETag, perhaps don't set it?

**Comment by ties** [comment]
> > My intuition is to stay away from strategy 2 - iirc a repository may contain non-RPKI files.
> 
> Sure, aiming for 1.. 2 would only ever work with a fallback to 1.

And I have gone full circle on this: Consider the situation with multiple nodes behind a load-balancer (as we are likely to do). By default any request can land at any of the machines behind the load-balancer (without considering consistent hashing or rendezvous hashing).

To prevent the modification time changing on all files for every new revision written (as it is right now), the nodes need the same timestamp for each file.

I guess approach (1) can never do that while it is a property of (2).

We use a similar approach for our current repository writing: We take the timestamp the object was 'published at'. Unfortunately RRDP repositories do not contain something like that...


> Right.. different issue, but replying here.. so far 'If-None-Match' seems to work just fine on the RIPE NCC notification.xml, but then again I hit the CDN and not the back-end servers. The cost of doing an extra fetch from krill-sync is not too bad I would think though - it can work out based on the session and serial that no work is needed.
> 
> What I can do is fall back to 'If-Modified-Since' if no 'ETag' was received. According to RFC7232 there is no point in specifying both together: https://datatracker.ietf.org/doc/html/rfc7232#section-3.3
> 
> Then.. well if your cluster cannot give me a reliable ETag, perhaps don't set it?

I was thinking about `If-None-Match` and `ETag`s for files read from different machines behind a load-balancer (not for krill-sync as a client). I expect there to be many more clients reading from a krill-sync node than requests from krill-sync -> origin.

If you have two machines behind a load-balancer, both would need to have the same modification time and `ETag` (iff the webserver uses the modification timestamp, which apparently is allowed) for things to work as you expect.

I think I should just write down a draft on some deployment considerations for RRDP and rsync repositories. I do not think these caching issues (as well as the need for 'long-lived consistent copies' instead of atomically consistent rsync repositories) is written down anywhere.

**Comment by timbru** [comment]
After measuring running this on a copy of the nic.br repository (using local files as input) I found that setting the time based on parsed objects rather than 'now' when the object was first seen, makes next to no difference - it was unmeasurable on my machine.

So in short I figured that we do not need an option for this and krill-sync will just base the mtime on parsed objects. This is still best effort. If parsing an object fails a warning is issued and the time when the object was first encountered is used instead.

Note: we currently do not fix directory times. I believe this is not needed for rsync since it doesn't really care about directories - it synchronises individual files.
